cloud:
  group: Base
  name: StorageWebServer
  logo: assets/logo.png
  version: latest
  changelist: Changelist.md
  lang: nodejs
  description: >-
    .
  description_cn: >-
    存储服务的数据管理平台, 能够管理数据.
  collaborators:
    - ruanshudong@qq.com
  repository: https://github.com/TarsCloudMarket/StorageWebServer.git
  readme: README.en.md
  readme_cn: README.md
  container: tars.nodejsbase
  protocols: []
  assets:
    - assets
app: Base
server: StorageWebServer
template: tars.nodejs
profile: ""
servants:
  - name: WebObj
    port: 10000
    isTars: false
    isTcp: true
    thread: 3
    capacity: 100000
    connection: 10000
    timeout: 30000
replicas: 2
hostNetwork: false
hostIPC: false
hostPorts: []
repo:
  id:
  image: ruanshudong/base.storagewebserver
  secret: cloud-market-secret
config:
  - name: config.json
    content: |
      {
          "dbConf": {
              "database": "db_storage_config",
              "model": "db_storage_config",
              "host": "127.0.0.1",
              "port": "3306",
              "user": "tarsAdmin",
              "password": "Tars@2019",
              "charset": "utf8mb4",
              "pool": {
                  "max": 10,
                  "min": 0,
                  "idle": 10000
              }
          },
          "port": "4300",
          "path": "/plugins/base/storage"
      }
